/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WebCard } from "./components/web-card-summary/web-card-summary";
import { InputType } from "./components/web-fieldset/web-fieldset";
import { RadioProps } from "./components/web-radio-input/web-radio-input";
import { RadioProps as RadioProps1 } from "./components/web-radio-input/web-radio-input";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebCardSummary {
        "cardSummary": WebCard;
    }
    interface WebFieldset {
        "inputType": InputType;
        "legendText": string;
        "options": RadioProps[];
        "slotLabel": boolean;
    }
    interface WebRadioInput {
        "webRadioProps": RadioProps;
    }
    interface WebSelectCardForm {
    }
    interface WebSelectTypeForm {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebCardSummaryElement extends Components.WebCardSummary, HTMLStencilElement {
    }
    var HTMLWebCardSummaryElement: {
        prototype: HTMLWebCardSummaryElement;
        new (): HTMLWebCardSummaryElement;
    };
    interface HTMLWebFieldsetElement extends Components.WebFieldset, HTMLStencilElement {
    }
    var HTMLWebFieldsetElement: {
        prototype: HTMLWebFieldsetElement;
        new (): HTMLWebFieldsetElement;
    };
    interface HTMLWebRadioInputElement extends Components.WebRadioInput, HTMLStencilElement {
    }
    var HTMLWebRadioInputElement: {
        prototype: HTMLWebRadioInputElement;
        new (): HTMLWebRadioInputElement;
    };
    interface HTMLWebSelectCardFormElement extends Components.WebSelectCardForm, HTMLStencilElement {
    }
    var HTMLWebSelectCardFormElement: {
        prototype: HTMLWebSelectCardFormElement;
        new (): HTMLWebSelectCardFormElement;
    };
    interface HTMLWebSelectTypeFormElement extends Components.WebSelectTypeForm, HTMLStencilElement {
    }
    var HTMLWebSelectTypeFormElement: {
        prototype: HTMLWebSelectTypeFormElement;
        new (): HTMLWebSelectTypeFormElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "web-card-summary": HTMLWebCardSummaryElement;
        "web-fieldset": HTMLWebFieldsetElement;
        "web-radio-input": HTMLWebRadioInputElement;
        "web-select-card-form": HTMLWebSelectCardFormElement;
        "web-select-type-form": HTMLWebSelectTypeFormElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebCardSummary {
        "cardSummary": WebCard;
    }
    interface WebFieldset {
        "inputType": InputType;
        "legendText": string;
        "options": RadioProps[];
        "slotLabel": boolean;
    }
    interface WebRadioInput {
        "webRadioProps": RadioProps;
    }
    interface WebSelectCardForm {
    }
    interface WebSelectTypeForm {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "web-card-summary": WebCardSummary;
        "web-fieldset": WebFieldset;
        "web-radio-input": WebRadioInput;
        "web-select-card-form": WebSelectCardForm;
        "web-select-type-form": WebSelectTypeForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-card-summary": LocalJSX.WebCardSummary & JSXBase.HTMLAttributes<HTMLWebCardSummaryElement>;
            "web-fieldset": LocalJSX.WebFieldset & JSXBase.HTMLAttributes<HTMLWebFieldsetElement>;
            "web-radio-input": LocalJSX.WebRadioInput & JSXBase.HTMLAttributes<HTMLWebRadioInputElement>;
            "web-select-card-form": LocalJSX.WebSelectCardForm & JSXBase.HTMLAttributes<HTMLWebSelectCardFormElement>;
            "web-select-type-form": LocalJSX.WebSelectTypeForm & JSXBase.HTMLAttributes<HTMLWebSelectTypeFormElement>;
        }
    }
}
